### ISSUE TITLE
"from kien import __version__" fails during "pip install kien"

### ISSUE THREAD

**Issue by sumpfralle** [silicann/kien#1]
Currently many convenience imports are available directly in `kien`:
```
from .commands import CommandResult, create_commander, group, keyword, optional, var  # noqa: F401
from .validation import validate  # noqa: F401
from .transformation import transform  # noqa: F401
from .error import CommandError, ItemNotFoundError, ParseError  # noqa: F401
```

This causes problems during `pip install`, since `setup.py` imports `kien` during the configuration phase (while *blessings* and *blinken* are not guaranteed to be available, yet).

I guess we have the following options:
* A) embed the version directly into `setup.py` (via `.bumpversion.cfg`)
* B) ensure, that no modules depending on `blessings` and `blinker` are imported in `kien`
* C) somehow configure both modules as *pre-dependencies* (if this is possible) in `setup.py`
* D) remove the convenience imports from `kien`
* E) move the convenience imports somewhere else

I would prefer D (since I do not like convenience imports, anyway).

**Comment by kmohrf** [comment]
fixed in 0.15.2 :)
